apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: elasticsearch-data-quickstart-es-default-0

