apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: canary
    service: canary
  name: istio-canary
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: canary
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary
    version: v2
  name: canary-v2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: canary
      version: v2
  template:
    metadata:
      labels:
        app: canary
        version: v2
    spec:
      containers:
      - image: supergiantkir/animals:bear
        name: canary
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: canary
    version: v1
  name: canary-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary
      version: v1
  template:
    metadata:
      labels:
        app: canary
        version: v1
    spec:
      containers:
      - image: supergiantkir/animals:moose
        name: canary
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy-proxy
  name: envoy-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: envoy-proxy
    spec:
      containers:
      - image: envoyproxy/envoy:v1.11.2
        imagePullPolicy: Always
        name: envoy
        command: ["/usr/local/bin/envoy"]
        args: ["-c","/tmp/config.yaml"]
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: config
          mountPath: "/tmp"
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: config
        secret:
          secretName: envoy-conf
          optional: false
---
apiVersion: v1
data:
  config.yaml: YWRtaW46CiAgYWNjZXNzX2xvZ19wYXRoOiAvZGV2L251bGwgIy90bXAvYWRtaW5fYWNjZXNzLmxvZwogIGFjY2Vzc19sb2c6CiAgLSBuYW1lOiBlbnZveS5hY2Nlc3NfbG9nZ2Vycy5zdGRvdXQKICAgIHR5cGVkX2NvbmZpZzoKICAgICAgIkB0eXBlIjogdHlwZS5nb29nbGVhcGlzLmNvbS9lbnZveS5leHRlbnNpb25zLmFjY2Vzc19sb2dnZXJzLnN0cmVhbS52My5TdGRvdXRBY2Nlc3NMb2cKICBhZGRyZXNzOgogICAgc29ja2V0X2FkZHJlc3M6CiAgICAgIHByb3RvY29sOiBUQ1AKICAgICAgYWRkcmVzczogMC4wLjAuMAogICAgICBwb3J0X3ZhbHVlOiA5OTAxCnN0YXRpY19yZXNvdXJjZXM6CiAgbGlzdGVuZXJzOgogIC0gbmFtZTogbGlzdGVuZXJfMAogICAgYWRkcmVzczoKICAgICAgc29ja2V0X2FkZHJlc3M6CiAgICAgICAgcHJvdG9jb2w6IFRDUAogICAgICAgIGFkZHJlc3M6IDAuMC4wLjAKICAgICAgICBwb3J0X3ZhbHVlOiA4MAogICAgZmlsdGVyX2NoYWluczoKICAgIC0gZmlsdGVyczoKICAgICAgLSBuYW1lOiBlbnZveS5odHRwX2Nvbm5lY3Rpb25fbWFuYWdlcgogICAgICAgIHR5cGVkX2NvbmZpZzoKICAgICAgICAgICJAdHlwZSI6IHR5cGUuZ29vZ2xlYXBpcy5jb20vZW52b3kuY29uZmlnLmZpbHRlci5uZXR3b3JrLmh0dHBfY29ubmVjdGlvbl9tYW5hZ2VyLnYyLkh0dHBDb25uZWN0aW9uTWFuYWdlcgogICAgICAgICAgc3RhdF9wcmVmaXg6IGluZ3Jlc3NfaHR0cAogICAgICAgICAgcm91dGVfY29uZmlnOgogICAgICAgICAgICBuYW1lOiBnb29nbGVfX3JvdXRpbmcKICAgICAgICAgICAgdmlydHVhbF9ob3N0czoKICAgICAgICAgICAgLSBuYW1lOiBiYWNrZW5kCiAgICAgICAgICAgICAgZG9tYWluczogWyIqIl0KICAgICAgICAgICAgICByb3V0ZXM6CiAgICAgICAgICAgICAgLSBtYXRjaDoKICAgICAgICAgICAgICAgICAgcHJlZml4OiAiLyIKICAgICAgICAgICAgICAgIHJvdXRlOgogICAgICAgICAgICAgICAgICBjbHVzdGVyOiBzZXJ2aWNlX2dvb2dsZQogICAgICAgICAgICAgICAgICBwcmVmaXhfcmV3cml0ZTogIi8iCiAgICAgICAgICAgICAgICAgIGhvc3RfcmV3cml0ZTogIi4qIgogICAgICAgICAgaHR0cF9maWx0ZXJzOgogICAgICAgICAgLSBuYW1lOiBlbnZveS5yb3V0ZXIKICBjbHVzdGVyczoKICAtIG5hbWU6IHNlcnZpY2VfZ29vZ2xlCiAgICBjb25uZWN0X3RpbWVvdXQ6IDEwcwogICAgdHlwZTogU1RSSUNUX0ROUwogICAgIyBDb21tZW50IG91dCB0aGUgZm9sbG93aW5nIGxpbmUgdG8gdGVzdCBvbiB2NiBuZXR3b3JrcwogICAgZG5zX2xvb2t1cF9mYW1pbHk6IFY0X09OTFkKICAgIGxiX3BvbGljeTogUk9VTkRfUk9CSU4KICAgIGxvYWRfYXNzaWdubWVudDoKICAgICAgY2x1c3Rlcl9uYW1lOiBzZXJ2aWNlX2dvb2dsZQogICAgICBlbmRwb2ludHM6CiAgICAgIC0gbGJfZW5kcG9pbnRzOgogICAgICAgIC0gZW5kcG9pbnQ6CiAgICAgICAgICAgIGFkZHJlc3M6CiAgICAgICAgICAgICAgc29ja2V0X2FkZHJlc3M6CiAgICAgICAgICAgICAgICBhZGRyZXNzOiBpc3Rpby1jYW5hcnkuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbAogICAgICAgICAgICAgICAgcG9ydF92YWx1ZTogODAK
kind: Secret
metadata:
  name: envoy-conf
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy-proxy
  name: envoy-proxy
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 32084
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: envoy-proxy
  sessionAffinity: None
  type: LoadBalancer
