apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
  namespace: default
data:
  index.html: |-
    <html>
    <head>
        A simple Index.html
    </head>
    <body>
        <BR> <b>Hello Nginx</b>
        <BR> This is a simple index.html
    </body>
    </html>



