apiVersion: v1
kind: Namespace
metadata:
  name: pinniped-supervisor
  labels:
    app: pinniped-supervisor
---
apiVersion: v1
data:
  GlobalSign.crt: LS0tLS1CRUd...0Y3BICldEOWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  GlobalSignIntermidiate.crt: LS0tLS1CRUd...0Y3BICldEOWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  CompanyRootCA.crt: LS0tLS1CRUd...0Y3BICldEOWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  CompanyIntermidiate.crt: LS0tLS1CRUd...0Y3BICldEOWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ
  proxy.crt: LS0tLS1CRUd...0Y3BICldEOWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ
  SomeOtherCRT.crt: LS0tLS1CRUd...0Y3BICldEOWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ
kind: Secret
metadata:
  name: company-cert-tls
  namespace: pinniped-supervisor
type: Opaque
