apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
   name: supervisor-jwt-authenticator
   namespace: pinniped-concierge
spec:
   issuer: https://k8soidc.levys.co.il/auth/oidc
   audience: jCIGaxMT5Yw9NvafTTVoXxGLkviPPyg6
   claims:
     username: username
     groups: groups
   tls:
     certificateAuthorityData: <CERTIFICATE FROM STOP 09>

